// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js commonly uses `.env.local`, but Prisma CLI only auto-loads `.env` via `dotenv/config`.
// Load local overrides first, then fall back to `.env`.
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" });

// Migrations/introspection need a direct Postgres URL. Accelerate URLs
// (`prisma+postgres://` / `prisma://`) are for the app client only.
const migrateUrl =
  process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"];

/** Optional dedicated Postgres DB for `prisma migrate diff --from-migrations ...` shadow applies (CI validation). */
const shadowDatabaseUrl = process.env["SHADOW_DATABASE_URL"]?.trim();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrateUrl,
    ...(shadowDatabaseUrl ? { shadowDatabaseUrl } : {}),
  },
});
